### ISSUE TITLE
CI with warnings

### ISSUE THREAD

**Issue by jzwar** [tataratat/splinepy#102]
There seems to be some functionality in our CI, that is deprecated. 
Check the warning, e.g., [here](https://github.com/tataratat/splinepy/actions/runs/4141991588)

```
build_and_tests (3.8, ubuntu-20.04)
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using 
Environment Files. For more information see: 
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

Would some of the CI expert please check this out :D

**Comment by jzwar** [comment]
Is there any progress on this? This still seems to be an issue, see e.g., [here](https://github.com/tataratat/splinepy/actions/runs/4312993924)

**Comment by deltaLuki** [comment]
GitHub has [introduced a new set of environment files](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) for actions. To fix, we have to change the` setup-python@v3` to `setup-python@v4`
