### ISSUE TITLE
Add Cartesian is broken

### ISSUE THREAD

**Issue by jzwar** [tataratat/splinepy#123]
```python
import splinepy as sp
import numpy as np
sp.utils.data.cartesian_product([np.array([0,1,2]),np.array([0,2,4])])
```

Error:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zwar/Git/gustav_dev/splinepy/splinepy/utils/data.py", line 312, in cartesian_product
    dim_reducing_views[i][..., i] = arrays[i][idx[: n_arr - i]]
ValueError: could not broadcast input array from shape (3,) into shape (2,)

**Comment by jzwar** [comment]
The problem seems to be the reverse option.

**Comment by jzwar** [comment]
https://github.com/tataratat/splinepy/pull/120/commits/b1783e0494924e48891bf455f44f8835f1667a49
Bug should be fixed with this

**Comment by jzwar** [comment]
I can create a different branch with the bugfix only if you want @j042

**Comment by j042** [comment]
ufff, good catch. I changed to one if from two ifs right before commit and that was a bad move. I will cherry-pick and extend the test!
