### ISSUE TITLE
spline init with modified spline

### ISSUE THREAD

**Issue by j042** [tataratat/splinepy#136]
initializing a spline with a spline will takes backend spline, even if the spline has local changes.  
Undesired behavior

**Comment by jzwar** [comment]
is also a problem when trying to copy a spline that has not been in use in gustaf.

**Comment by j042** [comment]
> is also a problem when trying to copy a spline that has not been in use in gustaf.

could you give me a simple example?

**Comment by jzwar** [comment]
```python
import gustaf as gus
tt = gus.Bezier(degrees=[1],control_points=[[0,],[1,]])
tt.copy()
```
produces
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path>/gustaf/spline/base.py", line 224, in copy
    new.new_core(**self._data["properties"], properties_round_trip=False)
  File "<path>/splinepy/spline.py", line 794, in new_core
    raise RuntimeError(
RuntimeError: dict_keys(['properties_round_trip']) is not valid set of keywords to create a new core for Bezier.Valid ones should include: ('degrees', 'control_points').

**Comment by j042** [comment]
that part is not valid anymore after [this](https://github.com/tataratat/gustaf/pull/116). try the main branch. meanwhile, I will try to bump the version

**Comment by jzwar** [comment]
Seems to work now after, applying #138
