### ISSUE TITLE
Remove knots fails with first and last knot

### ISSUE THREAD

**Issue by jzwar** [tataratat/splinepy#215]
Minimal example:
```
import splinepy as sp

# Create a simple spline
a = sp.BSpline([1],[[0,0,1,2,2]],[[0],[1],[2]])
# Remove first knot (optional)
a.remove_knots(0,[1]) # works just fine
# Error 
a.remove_knots(0,[0]) # Segfault
# Similarly
a.remove_knots(0,[2]) # Segfault
```

**Comment by deltaLuki** [comment]
If you compile splinepy in `debug` mode and run this, you will see that `SplineLib` throws the following exception:
`ValueError: bsplinelib::parameter_spaces::ParameterSpace::RemoveKnot: Throws the following —> for dimension 0: for dimension0: Cannot insert or remove the first or last knot 2.000000 as only clamped knot vectors are allowed.`

**Comment by jzwar** [comment]
Yes, but IMO, throwing exceptions only in debug mode is like an assertion. Exceptions should also be thrown if the user inputs faulty data. Especially, as we provide wheels that are built in release mode. Just some random segfault should never occur!

**Comment by deltaLuki** [comment]
> Yes, but IMO, throwing exceptions only in debug mode is like an assertion. Exceptions should also be thrown if the user inputs faulty data. Especially, as we provide wheels that are built in release mode. Just some random segfault should never occur!

This is because `#ifndef NDEBUG` is used in the `SplineLib`. Do you think we should do our own checks inside `splinepy`? However, this would mean that the values are checked twice. Once in `splinepy` and once in `SplineLib`.

**Comment by jzwar** [comment]
@danielwolff1

**Comment by j042** [comment]
@danielwolff1

**Comment by danielwolff1** [comment]
I'll look into that after I'm back from Munich

**Comment by jzwar** [comment]
Maybe also a good start if C^(-1) is implemented :heart:
