### ISSUE TITLE
Make Interpolate Curve Static templated function

### ISSUE THREAD

**Issue by jzwar** [tataratat/splinepy#24]
Extend interpolation to All SplineTypes using static templated methods

**Comment by j042** [comment]
let's not make it template

**Comment by jzwar** [comment]
#62 ?

**Comment by j042** [comment]
would you like to implement/adjust this for all spline types?

**Comment by j042** [comment]
included in #66

**Comment by j042** [comment]
implemented as class method at python side
#62
