### ISSUE TITLE
Incorrect orientation if when the patches are rotated by PI-radians

### ISSUE THREAD

**Issue by deltaLuki** [tataratat/splinepy#269]
When the axes of two patches are rotated by pi radians, an incorrect orientation is calculated. In the following example, an alignment of [1, 0] and an orientation of [0, 0] are calculated. However, in my opinion, it should result alignment of [1, 0] and an orientation of [1, 1].

The following test case fails because of the wrong orientations:
```
def test_orientation_rotated_pi_radians(self):
        # Init Splines to be tested
        a_s = c.splinepy.Bezier(
            degrees=[1, 1], control_points=[[1, 1], [1, 2], [2, 1], [2, 2]]
        )
        b_s = c.splinepy.Bezier(
            degrees=[1, 1], control_points=[[2, 3], [1, 3], [2, 2], [1, 2]]
        )


        # Expected Values
        expected_interfaces = [
            [-1, 7, -1, -1],
            [-1, -1, -1, 1],
        ]

        expected_orientations = [
            [0, 1, 1, 3, 1, 0, 1, 1],
        ]

        # Provide connectivity data
        mp = c.splinepy.Multipatch([a_s, b_s])

        # First compare interfaces to what is expected
        interfaces = mp.interfaces
        self.assertTrue(c.np.all(interfaces == expected_interfaces))

        # Then check orientations
        orientations = mp.interface_orientations()
        self.assertTrue(c.np.all(orientations == expected_orientations))
```

**Comment by j042** [comment]
is this part of an existing test? `a_s` and `b_s` are flipped - jacobian determinants will be negative and you should at least use splines that aren't flipped

**Comment by deltaLuki** [comment]
> is this part of an existing test? `a_s` and `b_s` are flipped - jacobian determinants will be negative and you should at least use splines that aren't flipped

No, this is a test from me. Does this mean that we don't need to consider the case where the patches are rotated 180 degrees?

**Comment by j042** [comment]
see `Quick Start`

> ...
> The indexing of the control grid is defined by iterating
> lower-indexed dimensions first. But if you prefer a
> ...

splines in your test case aren't doing that.

**Comment by jzwar** [comment]
Jacobians can be negative for multipatch geometries in these tests, as only the orientation is compared. However, I think the expected orientations vector might be wrong. From a quick drawing on a napkin I get
```
[0, 1, 1, 3, 1, 0, -1, -1]
```

**Comment by j042** [comment]
Nice. If you wanna add such test, please explicitly mark as negative jacobian multipatch test
