### ISSUE TITLE
Plotting functions on splines is too complicated

### ISSUE THREAD

**Issue by jzwar** [tataratat/splinepy#291]
Plotting a function on a spline is very complicated at the moment, as every time the `resolution` and `on` case need to be dealt with. It is not possible to just plot the same function on a Multipatch. That makes it very hard for new users to understand.

I think it would be nice to have a layout like this

```python
def foo(spline, queries):
  # Function in physical space
  x = spline.evaluate(queries)
  return x*x

def bar(spline, queries):
  # Function defined in parametric space
  return queries*queries
```

**Comment by j042** [comment]
#318
