### ISSUE TITLE
Missing splinepy bindings

### ISSUE THREAD

**Issue by jakhau** [tataratat/splinepy#32]
Some functions that still need bindings to be used in splinepy:

- [ ] Conversions between NURBS and Bezier/ rational Bezier
- [ ] Derivative evaluation of Bezier/ rational Bezier
- [ ] Output of basis functions for Bezier/ rational Bezier (might not be important anyways)
- [ ] Reduce_order function for Bezier/ rational Bezier

**Comment by j042** [comment]
I don't think we will be working on those points in the near future.  
If you decide to work on it, feel free to reopen this!
