### ISSUE TITLE
Adapt to incomming changes to gustaf

### ISSUE THREAD

**Issue by clemens-fricke** [tataratat/splinepy#323]
Gustaf is removing the backend option (tataratat/gustaf#171) in most places and will from now on only use `vedo` as its visualization backend. This change necessitates some changes to splinepy's code base.

The needed changes are mainly in `splinepy/helpme/visualize.py`.

1. Remove references to SplineShowOption._backend
2. Make sure to make the Option definition into an iterable by having for single type options a comma after the element `(int)` -> `(int,)`

**Comment by j042** [comment]
#311
