### ISSUE TITLE
Pictures in documentation

### ISSUE THREAD

**Issue by jzwar** [tataratat/splinepy#366]
The pictures are only shown in the local build, but somehow the online build is different:

[here](https://tataratat.github.io/splinepy/_generated/splinepy.io.svg.export.html#splinepy.io.svg.export) should be a picture, it should look like this:
![image](https://github.com/tataratat/splinepy/assets/63095162/4fae9026-e8d1-4645-bd25-92ff8f3df771)

@clemens-fricke, I know I messed this up, but could you help me fix this?

**Comment by j042** [comment]
#368
