### ISSUE TITLE
Issue with Matrix solve

### ISSUE THREAD

**Issue by jzwar** [tataratat/splinepy#385]
There seems to be an issue with our implementation of Gausselimination with partial pivoting. I added this block to `Solve()` in `include/splinepy/utils/array.hpp` 

```cpp
#ifndef NDEBUG
    double norm{};
    for (IndexType i{}; i < len; ++i) {
      double row_val{};
      for (IndexType j{}; j < len; ++j) {
        row_val += array_copy(i, j) * x[j];
      }
      row_val -= b_copy[i];
      norm += row_val * row_val;
    }
    if (std::sqrt(norm) > 1e-4) {
      splinepy::utils::PrintAndThrowError("Solving failed, error is ", norm);
    }
#endif
```
It throws a lot. There is no testing of this. So far I haven't figured out where the bug is yet.

**Comment by jzwar** [comment]
Do you have any ideas @j042 ? Is my test wrong?

**Comment by jzwar** [comment]
The error only occurs when pivoting is used

**Comment by jzwar** [comment]
@j042 : Found the bug

**Comment by j042** [comment]
Thank you!
#386
