### ISSUE TITLE
Issues with Proximity

### ISSUE THREAD

**Issue by jzwar** [tataratat/splinepy#389]
Example with non-successful inverse searches:
```python
import splinepy as spp
import numpy as np

# Create a spline
spline = spp.Bezier(
    degrees=[2, 2],
    control_points=np.array([
        [0.0, 0.0],
        [0.2, -1.0],
        [2.0, 0.0],
        [0.0, 0.2],
        [0.2, 0.2],
        [1.5, 0.2],
        [0.0, 1.0],
        [0.2, 2.0],
        [1.0, 1.0]
    ])
)

# Make sure results are always available
solution = spp.utils.data.cartesian_product(
    [np.linspace(0, 1, 10) for _ in range(2)])
queries = spline.evaluate(solution)

# Search inverses
nearest = spline.proximities(
    queries=queries,
    max_iterations=200,
    initial_guess_sample_resolutions=[5, 5]
)

# Output
print(
    f"Proximity failed for points: "
    f"{np.where(np.linalg.norm(solution - nearest, axis=1) > 1e-7)[0]}"
)
```

`Proximity failed for points: [10 21 30 38 41 51 58 60 61 62 63 68 78 81 82 83 85 86 88]`

Increasing the number of samples creates more hits, however, this should always work, imo. Even with only 3 starting points.

Issues:
- [ ] Fix example
- [ ] Clean up unused functions (`GaussWithPivot`)

Check out #386 for more information

**Comment by jzwar** [comment]
I implemented a crude version of the Levenberg-Marquardt-method, based on [this](https://www.igpm.rwth-aachen.de/Numa/NumaMB/SS10/LevMarq.pdf). It significantly reduces the number of failures to:
`[11 21 61 62 81 82 88]` with the same example. It also uses a secondary metric from ILSB's numerics course ([here](https://github.com/tataratat/splinepy/blob/68edef6de3f1652f106a62aba92d664f5555636f/src/proximity/proximity.cpp#L384) as supposed to [here](https://github.com/tataratat/splinepy/blob/68edef6de3f1652f106a62aba92d664f5555636f/src/proximity/proximity.cpp#L380)), which seems to perform better.

There are two versions with a boolean flag [here](), where either the `lambda * diag(J^TJ)` is added or `lambda * I`, as shown in the wiki article. I did not observe any meaningful difference.

If only LM is used the failures are these:
`[ 1 11 19 20 21 29 31 61 62 80 81 82 88 91]`


@j042 : Is this worth further investigation?

**Comment by jzwar** [comment]
> I implemented a crude version of the Levenberg-Marquardt-method, based on [this](https://www.igpm.rwth-aachen.de/Numa/NumaMB/SS10/LevMarq.pdf). It significantly reduces the number of failures to: `[11 21 61 62 81 82 88]` with the same example. It also uses a secondary metric from ILSB's numerics course ([here](https://github.com/tataratat/splinepy/blob/68edef6de3f1652f106a62aba92d664f5555636f/src/proximity/proximity.cpp#L384) as supposed to [here](https://github.com/tataratat/splinepy/blob/68edef6de3f1652f106a62aba92d664f5555636f/src/proximity/proximity.cpp#L380)), which seems to perform better.
> 
> There are two versions with a boolean flag here, where either the `lambda * diag(J^TJ)` is added or `lambda * I`, as shown in the wiki article. I did not observe any meaningful difference.
> 
> If only LM is used the failures are these: `[ 1 11 19 20 21 29 31 61 62 80 81 82 88 91]`
> 
> @j042 : Is this worth further investigation?

Side-note. If we do not change the penalisation damping parameter, even if the coefficient `rho` is out of bounds, but only when the solution gets worse, it converges for all points. This is the latest version in the branch

**Comment by j042** [comment]
> > I implemented a crude version of the Levenberg-Marquardt-method, based on [this](https://www.igpm.rwth-aachen.de/Numa/NumaMB/SS10/LevMarq.pdf). It significantly reduces the number of failures to: `[11 21 61 62 81 82 88]` with the same example. It also uses a secondary metric from ILSB's numerics course ([here](https://github.com/tataratat/splinepy/blob/68edef6de3f1652f106a62aba92d664f5555636f/src/proximity/proximity.cpp#L384) as supposed to [here](https://github.com/tataratat/splinepy/blob/68edef6de3f1652f106a62aba92d664f5555636f/src/proximity/proximity.cpp#L380)), which seems to perform better.
> > There are two versions with a boolean flag here, where either the `lambda * diag(J^TJ)` is added or `lambda * I`, as shown in the wiki article. I did not observe any meaningful difference.
> > If only LM is used the failures are these: `[ 1 11 19 20 21 29 31 61 62 80 81 82 88 91]`
> > @j042 : Is this worth further investigation?
> 
> Side-note. If we do not change the penalisation damping parameter, even if the coefficient `rho` is out of bounds, but only when the solution gets worse, it converges for all points. This is the latest version in the branch

Thanks a lot for implementing this, sounds great to me!

**Comment by j042** [comment]
I had a weird case where `max_iterations` value was set to `0` at ~60 query within a call. This happened at `PySpline::Proximities`. I wonder if that was compiler error or something that happens due to our implementation.
