### ISSUE TITLE
Create Spline-Patch-Group

### ISSUE THREAD

**Issue by jzwar** [tataratat/splinepy#63]
In order to describe complex geometries, more than one spline-patch is required. Currently they are stored as a simple list of splines. However, for analysis, more information might be required, such as:
- Connectivity information
- Boundary information
- (optional) material IDs

Having such a class, would facilitate the multipatch output for several IGA-solvers. It could further provide a few functions
- `show` for multipatch, storing already sampled geometries
- multithread `sample`-ing
- `select_boundary` for interactively chosing boundaries based on patch and face IDs

We should also make sure, that intermediate "designs" can be stored in json format, so boundaries can be stored and altered later!

This is related to `gismo`, `mfem` and `nutils` exports and might be of interest to the users of these softwares.

**Comment by jzwar** [comment]
Please leave a comment for discussion, as to what is required and what might be missing

**Comment by j042** [comment]
now #62 is merged those things should be easier to extend. `select_boundary` should be in `gustaf`

**Comment by j042** [comment]
#77

**Comment by jzwar** [comment]
#94
