### ISSUE TITLE
Spice up the Readme.md file

### ISSUE THREAD

**Issue by jzwar** [tataratat/splinepy#65]
We should extend the Readme.md file and add some information for newcomers. 

Ideas can be collected in this thread:
- [x] CI & CD status with more detail 
- [ ] Gustaf Logo
- [x] Link to documentation
- [x] Link to thirdparty librarires
- [x] Feature list
- [ ] Citing information
- [x] Link to contribution info
- [x] Some details

**After all, it is the very first thing people will check out**

**Comment by j042** [comment]
sounds good, go ahead!
