### ISSUE TITLE
DISCUSSION: CodeSpaces

### ISSUE THREAD

**Issue by jzwar** [tataratat/splinepy#97]
Recently, Github started to offer codespaces with 60-120 core hours a month for free. Would this maybe be an opportunity to provide jupyter notebooks to test virtually prior to downloading or installing splinepy? I think this would make a good marketing strategy :wink: 

I still have to figure out the details, just wanted to throw it in the ring

**Comment by jzwar** [comment]
Same goes for gustaf, but there it is maybe harder to maintain due to the visualization stuff

**Comment by j042** [comment]
For discussions, there's a cool [GitHub feature](https://github.com/tataratat/splinepy/discussions). Feel free to move this there.
I don't think code space is suitable choice for that purpose. Instead, take a look at [this](https://mybinder.org/v2/gh/tataratat/try-splinepy/main). You can add some `.ipynb` [here](https://github.com/tataratat/try-splinepy).  
We can also add one for gustaf, after we take care of [this issue](https://github.com/tataratat/gustaf/issues/23).
